---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhanglong.
--- DateTime: 2019/7/1 20:07
---lua函数
print("==============lua函数==================")
function sum(a,b)
    return a+b
end
print(sum(1,2))

function func(a,b,c,d)
    return a+1,c+1
end
print(func(1,2,3))

print("================Lua table===============")
--Lua table 是不固定大小的，你可以根据自己需要进行扩容。
mytable = {}
mytable.first = "tom"
mytable.second = "james"

print(mytable[1])   --nil
print(mytable.first)    --tom
print(mytable.second)   --james

print("================Lua table===============")

module = {}
module.index = 1
function module.sum(a,b)
    return a+b
end
print(module.index)
print(module.sum(10,20))