---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhanglong.
--- DateTime: 2019/7/1 21:01
---获取http请求信息
local arg = ngx.req.get_uri_args()
    for k,v in pairs(arg) do
        ngx.say("[GET]key:",k,"v:",v)
        ngx.say("<br>")
    end