---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhanglong.
--- DateTime: 2019/7/2 17:52
---引入redis模块
local redis = require("resty.redis")

--创建redis实例
local red = redis:new()

--创建redis连接
local ok,err = red:connect("192.168.25.111",6379)
--ok是布尔值，如果连接成功，OK，true，连接失败，OK，false
if not ok then
    --连接失败
    ngx.say("connection redis is false:",err)
    return
end

--向redis写数据
local ok,err = red:set("itcast","itcast is heima")
if not ok then
    ngx.say("send message if faile",err)
    return
end
--打印成功写入redis的信息
ngx.say("send message ok")
