---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhanglong.
--- DateTime: 2019/7/1 20:28
---这是我们自定义模块（模拟kafka生产者），模块是由变量和函数产生，将变量和函数放在table中，将table返回
_M={}
--扩展一个默认分区属性
_M.default_partition_num=3

--模拟函数的初始化（生产者实例化）
function _M.new()
    return "producer"
end

--模拟一个发送消息的函数
function _M.sed(message)
    return "ok"
end

