---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhanglong.
--- DateTime: 2019/7/1 20:40
---调用生产者模块，发送消息到kafka
---使用require引入模块，不需要指定模块的后缀名，如果引入模块和当前的脚本问价不再同一个目录下，需要指定目录
require("Openresty_lua")
--打印模块的默认分区数
print(_M.default_partition_num)
--实例化生产者
print(_M.new())
--调用发送消息
print(_M.sed("hello"))
